version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: student_api_app
    ports:
      - "8000:8000"
    command: ["gunicorn", "--bind", "0.0.0.0:8000", "app:app"]
  nginx:
    image: nginx:alpine
    container_name: student_api_nginx
    ports:
      - "8080:80"
    volumes:
      - ./nginx-default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - app
